### ISSUE TITLE
kafka-quarkus-quickstart fails if docker daemon is missing or not running

### ISSUE THREAD

**Issue by hawkdshrh** [redhat-developer/app-services-guides#112]
The default build (mvn/mvnw clean install / package) fails if docker is not installed or running on the development host.

**Comment by wtrocki** [comment]
@hawkdshrh Yes. That would be quarkus limitation. I think we might move to JIB builds but when I tried last time we got some issues with those. Looking into this now.

**Comment by b1zzu** [comment]
Hi  @hawkdshrh, this issue should be now fixed on the main branch, can you reverified it

**Comment by wtrocki** [comment]
We have been doing verification for that issue continuously. Closing
