### ISSUE TITLE
OpenJDK on Windows doesn't have the right cert to connect to the Kafka instance

### ISSUE THREAD

**Issue by b1zzu** [redhat-developer/app-services-guides#113]
I don't know why but maybe the Windows OpenJDK doesn't come with any cert installed and therefore it can not connect to the Kafka instance, I think therefore we should suggest the user to use the Oracle JDK both for the Bin scripts and the Quarkus app

**Comment by wtrocki** [comment]
@b1zzu would verfiy and make change for you.

**Comment by wtrocki** [comment]
Update. I realized that I have been using Linux shell on windows which is different. @b1zzu you are using plain vanilla windows machine right?

**Comment by wtrocki** [comment]
Yes. Using Oracle JDK with SASL/Plain works 🔥 

@sterobin @bhardesty I think we should apply this change to all requirements. 

` - Requires latest version of Oracle JDK from Oracle Website` 

Localized URL for me was:
https://www.oracle.com/ie/java/technologies/javase-jdk11-downloads.html

**Comment by sterobin** [comment]
@b1zzu @wtrocki ack. Addressed in #118  Please review and verify.

**Comment by sterobin** [comment]
Merged #118 to address this. Closing.
