### ISSUE TITLE
Bootstrap server replacement in "bin script" quickstart

### ISSUE THREAD

**Issue by trepel** [redhat-developer/app-services-guides#116]
The "bin scripts" quickstart expects to replace <bootstrap_server> with the actual URL. But it does not say that explicitly so people might not notice and just use a command and get an error (the error message is descriptive enough though). Also, it does not say where to look at to see what the URL actually is.

**Comment by trepel** [comment]
Small addition, you can replace 2.7.0 version with 2.8.0 since it is already available in the quickstart text

**Comment by b1zzu** [comment]
> Small addition, you can replace 2.7.0 version with 2.8.0 since it is already available in the quickstart text
Because the Kafka instances deployed in 2.7.0 is better if the user downloads the 2.7.0 so we should just change `latest` with `2.7.0`

**Comment by sterobin** [comment]
@trepel @pmuir @jciroli-rh @bhardesty I commented in the gdoc that brought this up. It's the same recurring issue of the prerequisites being excluded in the UI. That info about where the bootstrap server is and the need to have it handy is covered in the prereqs in the docs, which are in the source and rendered in the Customer Portal version of the docs, but for some reason it was decided to exclude prereqs from the UI of the quick start doc content. This issue and several others would be resolved by allowing prereqs in the UI. I don't know enough about the history or rationale for excluding those, so deferring to @pmuir or @jciroli-rh  who might know and can answer.

**Comment by b1zzu** [comment]
More than understandable, if we have an issue for fixing the prereqs we can link it here and close this one

**Comment by sterobin** [comment]
@trepel @b1zzu I've opened a Jira for this here: https://issues.redhat.com/browse/MGDSTRM-3087  @jgiardino FYI, assigned to you.

**Comment by jgiardino** [comment]
For everyone's awareness, @sterobin also provided a short-term fix for the issue with the bootstrap prerequisite in this update: https://github.com/redhat-developer/app-services-guides/pull/128

**Comment by wtrocki** [comment]
After quick check I see that this seems to be resolved. Can we close this issue?

**Comment by sterobin** [comment]
IMO, yes, can be resolved.
