### ISSUE TITLE
Suggest using Docker or WSL for the Kafkacat quickstart in Windows

### ISSUE THREAD

**Issue by b1zzu** [redhat-developer/app-services-guides#125]
There is no prebuild executable of kakfacat for windows and is practically impossible to compile it, therefore we should suggest using the docker image, or install kafkacat on WSL

**Comment by b1zzu** [comment]
ping @sterobin

**Comment by wtrocki** [comment]
FYI @redhat-developer/app-services-docs We have now https://github.com/redhat-developer/app-services-tools

**Comment by sterobin** [comment]
@b1zzu Sorry that this got left in the dust. Is this still pertinent or now obsolete?

**Comment by sterobin** [comment]
I forgot that @b1zzu is no longer at Red Hat. Looking at other conversations about this in chats and meetings of last year, this comment seems obsolete. Closing.
