### ISSUE TITLE
quick starts can become entangled with each other

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer/app-services-guides#269]
Basically the Kafka bin quick start wishes to "assume control" of the user experience.  I tried 2 browsers so it seems the state is saved with the user id on the backend
https://www.screencast.com/t/MtvYsPcb

**Comment by wtrocki** [comment]
CC @jschuler

**Comment by jschuler** [comment]
I am trying to reproduce but have not been able to so far, @burrsutter if you open up an incognito window and log back in, is there a sequence where are you able to get it to that confused state again?
Also, in a window where you see the issue happening, would you be able to open up the browser dev tools and use this command
`copy(localStorage.getItem('quickstarts'))`
then paste the contents here?

Thanks!

**Comment by burrsutter** [comment]
I bet the issue is related to the fact that I have 2 accounts and I bounce between the two.  Chrome is the target for "rhoas login" and I sometimes forget to "rhoas logout".

**Comment by burrsutter** [comment]
And it does seem to behave normally now - good times :-)

**Comment by wtrocki** [comment]
Closing
