### ISSUE TITLE
"Quarkus guide contains Group ID"

### ISSUE THREAD

**Issue by cfullam1** [redhat-developer/app-services-guides#291]
Mentions a group id here,  it says consumers with the same id belong in the same group. Couldn't see where I find this id..

**Comment by wtrocki** [comment]
I think current guide is confusing as it requires user to setup consumer group as env variable. 
This is typically done in the properties. we can move values from env var (that requires user interaction) to property usage and still have documentation capability.

**Comment by wtrocki** [comment]
Update. Env var wasn't used. I settled to not set up consumer group property.
