### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by cben** [redhat-developer/app-services-guides#440]
https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1/guide/88e1487a-2a14-4b35-85b9-a7a2d67a37f3
in Prerequisites section:
> * You’ve installed the rhoas CLI. For more information, see [Installing the rhoas CLI](https://access.redhat.com/documentation/en-us/%7Bproduct-long-url-kafka%7D/%7Bproduct-version-kafka%7D/guide/fa4bad02-10f2-4ef3-be34-7edc1337e7ee).

that link is 404, correct URL seems to be
https://access.redhat.com/documentation/en-us/red_hat_openshift_application_services/1/guide/bb30ee92-9e0a-4fd6-a67f-aed8910d7da3

**Comment by cben** [comment]
the broken URL looks like percent-encoding of
`https://access.redhat.com/documentation/en-us/%7Bproduct-long-url-kafka%7D/%7Bproduct-version-kafka%7D/guide/fa4bad02-10f2-4ef3-be34-7edc1337e7ee` so I guess it got encoded before variables were substituted?

**Comment by sterobin** [comment]
@cben Correct. This has now been fixed. Thanks. Latest doc with functioning prereq link: https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1/guide/88e1487a-2a14-4b35-85b9-a7a2d67a37f3
