### ISSUE TITLE
can we get stable UUID-free link to Getting started with the CLI doc?

### ISSUE THREAD

**Issue by cben** [redhat-developer/app-services-guides#441]
[OCM downloads page](https://console.redhat.com/openshift/downloads#tool-rhoas) had a "Get started" link to  
https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1/guide/f520e427-cad2-40ce-823d-96234ccbc047 which returns 404.
I'm now updating it to  
https://access.redhat.com/documentation/en-us/red_hat_openshift_streams_for_apache_kafka/1/guide/88e1487a-2a14-4b35-85b9-a7a2d67a37f3 which seems to be the current URL for same doc.  But I worry the use of a UUID may cause it to change again in the future?  Can we assume that link stable, or can you provide a better permalink?

**Comment by wtrocki** [comment]
FYI @redhat-developer/app-services-docs

**Comment by sterobin** [comment]
@cben Correct, that UUID is fairly stable long term. The only reason that particular UUID changed is that we had to move the CLI documentation to a different repo in GitLab and re-publish, which did affect UUIDs. But this is not a normal occurrence, so in general, yes, the UUID is the current approach that Pantheon v2 (our downstream publishing tool) uses and is what can be linked to, as you've shown in your example.
