### ISSUE TITLE
Unify quarkus env and sbo guides

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-guides#82]
Currently we have 2 guides using the same codebase. 
There is simple way to do it currently:

For env variables we can use env files rather than application properties.
This is not only better practice. 

Guide for the env can require users to create env file with some content other wise quarkus kubernetes plugin config will kick in:

Reference:
https://quarkus.io/guides/config-reference

**Comment by wtrocki** [comment]
@pmuir 

what is your take on having codebase in some shared folder outside guides (as both guides will use it)

**Comment by pmuir** [comment]
something like /samples?

**Comment by wtrocki** [comment]
examples? :D

**Comment by pmuir** [comment]
I think that does make sense - it's a bit harder for the user as they now have to look at two directories

**Comment by wtrocki** [comment]
Ok.. Doing changes and unifying both env and SBO guides
