### ISSUE TITLE
Provide Node.js community guide and example

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-guides#84]
Refactoring done in the #82 will enable us to link also other guide (as subthree or commit it directly here) 
this way we could provide both Node.js and Quarkus examples.

What can be done:
1. Create Node.js SBO guide for Kafka
2. Link or commit sample Node.js Kafka application

CC @mhdawson

**Comment by wtrocki** [comment]
I will look into this with collaboration with Node.js team. If we can get link to potential application that can be used as base then we can start working on this

**Comment by mhdawson** [comment]
We should start with this sample - https://github.com/nodeshift-starters/reactive-example. We'll adjust it as necessary but is the one we currently have that users Kafka.

I already uses some environment variables, for example: https://github.com/nodeshift-starters/reactive-example/blob/dc1a52dc6ca3eb46e31562c9e98b8e4b72b19502/consumer-backend/consumer.js#L17

```JavaScript
  'metadata.broker.list': process.env.KAFKA_BOOTSTRAP_SERVER || 'my-cluster-kafka-bootstrap:9092',
```

**Comment by wtrocki** [comment]
I think we should do as follows:

1) Make it work with the Env variables ( this can be done only to your Kafka and since we have limits on this it is better for myself to adjust it and make guide

2) Collect requirements for file based/SBO specific npm module that will read files and expose config - if that is reasonable we need new GitHub repo for this and have discussion on this topic there.

**Comment by mhdawson** [comment]
Agreed those two things make sense. 

I think 1, may be as simple as updating the example to use 'KAFKACONNECTION_BOOTSTRAPSERVERS' instead of  KAFKA_BOOTSTRAP_SERVER, right ?

**Comment by mhdawson** [comment]
Except I guess unless some additional authentication is required, which is likely but even so, we should be able to make the sample expect the same environment variables.

**Comment by wtrocki** [comment]
> I think 1) may be as simple as updating the example to use 'KAFKACONNECTION_BOOTSTRAPSERVERS' instead of KAFKA_BOOTSTRAP_SERVER, right ?

Exactly + testing - we seen lots of issues with quarkus on ssl config etc.

**Comment by wtrocki** [comment]
Update. We have managed to make guide work with kafka.js and @mhdawson build extension that provides way to apply service binding. @mhdawson can provide more details for the sbo plugin that was created.

@mhdawson I think we need to figure out some minimal kafka.js based example/sample app wth some minimal UI that will be updated in future (similar to Quarkus sample we have currently in repo) we can integrate it as community sample and write guide for it (This can happen post summit). Technically we can copy sample to this repo and adjust it or use external repository link if needed.

**Comment by mhdawson** [comment]
Is this the Quarkus sample you are talking about or is it something else? - https://github.com/redhat-developer/app-services-guides/tree/main/kafka-quarkus-dev

**Comment by wtrocki** [comment]
Example is here
https://github.com/redhat-developer/app-services-guides/tree/main/code-examples/quarkus-kafka-quickstart

**Comment by mhdawson** [comment]
Thanks

**Comment by wtrocki** [comment]
See #227

**Comment by wtrocki** [comment]
Done
