### ISSUE TITLE
Proposed folder structure to make repo usable in upstream

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-guides#86]
Hi

Repository is being used for different purposes and I would like to see if we can clean up it little bit.
Also I think we might simply have different folder for the guide that is not quickstarts.  etc.

1) All guides that are cloudmosaic quickstarts should be in the quickstarts folder
2) Documentation like cli guide should be in the docs folder
3) Code samples should be in the examples folder (already agreed as part of the other issue ).
4) Openshift guides - temp - should be in console-quickstarts

This will need some tooling changes but it might be very good to clear things out for community to understand what comes where etc.

Having documentation in the docs folder will also allow us to render github pages for it if needed etc. while quickstarts will be typically in cloud.redhat.com etc.

**Comment by wtrocki** [comment]
@pmuir this might sounds like crazy idea considering summit time and our tooling relying on the folder structure but I wanted to draft it. I have wasted some time not understanding 3 different formats of th guides/docs etc. if we do proper folder structure we can document that in the readme for end user (contribution guide is not place for it)

**Comment by wtrocki** [comment]
CC @bhardesty

**Comment by pmuir** [comment]
1 & 2 - I'm not sure why the Command Line Interface guide isn't a quick start - it feels like it should be to me
3. I'm kinda ok with this but it's not ideal in my opinion - I still want to understand what's blocking us from keeping the code samples with the guides.
4. Agreed, and this is temporary

If we do create an upstream site we will want quick starts there as well.

So generally I'm not ok with these changes, particularly not in a rush.

**Comment by jciroli-rh** [comment]
> 1 & 2 - I'm not sure why the Command Line Interface guide isn't a quick start - it feels like it should be to me

@pmuir  -- We have been breaking the general content model for quick starts (something that appears in the UI in the context of the user) for MK, which is why this isn't a quick start in the same way "Getting Started ..." is. Ideally, we'd use a different term/content type and implementation for things that are not done in the UI, but that's a conversation post-Summit. @bhardesty

**Comment by pmuir** [comment]
@jciroli-rh I've not come across that definition of a quick start before... My understanding of them comes from https://docs.openshift.com/container-platform/4.7/web_console/creating-quick-start-tutorials.html#understanding-quick-starts_creating-quick-start-tutorials which just says "A quick start is a guided tutorial with user tasks.".

**Comment by wtrocki** [comment]
This seems to be stale. Repository has very strong connection with internal red hat ecosystem thus there is no flexibility to make any changes around structure.
