### ISSUE TITLE
Values from properties are not properly displayed in quickstarts

### ISSUE THREAD

**Issue by wtrocki** [redhat-developer/app-services-guides#94]
https://github.com/redhat-developer/app-services-guides/blob/main/.build/utils/quickstart-adoc.js

![Screenshot 2021-04-15 at 16 53 47](https://user-images.githubusercontent.com/981838/114902563-da599700-9e0d-11eb-96af-fe34b9a75a89.png)

**Comment by pmuir** [comment]
This works in staging and prod, it's just failing in the local dev env for some reason.

**Comment by ajaypratap003** [comment]
> This works in staging and prod, it's just failing in the local dev env for some reason.

@pmuir I don't have idea how attributes i..e readme.adoc file generate but I noticed why this issue happened.
{product-long} is calling before defined. Just need to shift {product-long} on top in the file.

current :

[id="chap-getting-started"]
= Getting Started with {product-long}
ifdef::context[:parent-context: {context}]
:context: getting-started

////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////


:community:
:imagesdir: ./images
:product-long: Application Services
:product: App Services
// Placeholder URL, when we get a HOST UI for the service we can put it here properly
:service-url: https://localhost:1234/
:property-file-name: app-services.properties

:signup-link: https://localhost:1234/
// Other upstream project names
:samples-git-repo: https://github.com/redhat-developer/app-services-guides

////
END GENERATED ATTRIBUTES
////

`Expected:` : need to shift attributes on top in file. 

////
START GENERATED ATTRIBUTES
WARNING: This content is generated by running npm --prefix .build run generate:attributes
////


:community:
:imagesdir: ./images
:product-long: Application Services
:product: App Services
// Placeholder URL, when we get a HOST UI for the service we can put it here properly
:service-url: https://localhost:1234/
:property-file-name: app-services.properties

:signup-link: https://localhost:1234/
// Other upstream project names
:samples-git-repo: https://github.com/redhat-developer/app-services-guides

////
END GENERATED ATTRIBUTES
////

[id="chap-getting-started"]
= Getting Started with {product-long}
ifdef::context[:parent-context: {context}]
:context: getting-started

**Comment by wtrocki** [comment]
Fixed
